-- Rend configurables les sujets/contenus des notifications portail (jusqu'ici
-- codés en dur dans DossierServiceImpl / InvestigationServiceImpl /
-- NotificationServiceImpl). {numero}, {motif}, {role} et {objet} sont
-- remplacés par les valeurs réelles au moment de l'envoi.

INSERT INTO portal_config
(config_key, config_value, label, description, value_type, group_name)
VALUES

('notif_subject_audio_alert',
 'ALERTE — Dénonciation audio à traiter',
 'Alerte agent — sujet',
 'Notification interne quand une dénonciation vocale est soumise',
 'TEXT', 'NOTIFICATIONS'),
('notif_content_audio_alert',
 'Un citoyen a soumis une dénonciation vocale. Veuillez écouter l''enregistrement et constituer le dossier.',
 'Alerte agent — contenu',
 'Notification interne quand une dénonciation vocale est soumise',
 'TEXT', 'NOTIFICATIONS'),

('notif_subject_protection_submitted',
 '⚠ PROTECTION LANCEUR D''ALERTE — Soumission reçue',
 'Protection à la soumission — sujet',
 'Notification interne quand la protection lanceur d''alerte est invoquée dès le dépôt',
 'TEXT', 'NOTIFICATIONS'),
('notif_content_protection_submitted',
 'Un déclarant a invoqué la protection lanceur d''alerte (Loi N°010-2004/AN) dès la soumission. Le dossier a été automatiquement marqué confidentiel.',
 'Protection à la soumission — contenu',
 'Notification interne quand la protection lanceur d''alerte est invoquée dès le dépôt',
 'TEXT', 'NOTIFICATIONS'),

('notif_subject_protection_registered',
 'PROTECTION LANCEUR D''ALERTE — Dossier {numero}',
 'Protection à l''enregistrement — sujet',
 'Notification interne à l''enregistrement du dossier. Utilisez {numero} pour insérer le numéro du dossier.',
 'TEXT', 'NOTIFICATIONS'),
('notif_content_protection_registered',
 'Le déclarant du dossier {numero} a invoqué la protection lanceur d''alerte (Loi N°010-2004/AN). Veuillez prendre les mesures de protection appropriées.',
 'Protection à l''enregistrement — contenu',
 'Notification interne à l''enregistrement du dossier. Utilisez {numero} pour insérer le numéro du dossier.',
 'TEXT', 'NOTIFICATIONS'),

('notif_subject_receipt_b4',
 'Récépissé de dépôt — {numero}',
 'Récépissé B4 — sujet',
 'Confirmation d''enregistrement envoyée au déclarant. Utilisez {numero} pour insérer le numéro du dossier.',
 'TEXT', 'NOTIFICATIONS'),
('notif_content_receipt_b4',
 'Votre dossier a été enregistré. Le code de suivi vous a été communiqué séparément lors de votre soumission.',
 'Récépissé B4 — contenu',
 'Confirmation d''enregistrement envoyée au déclarant',
 'TEXT', 'NOTIFICATIONS'),

('notif_subject_acknowledgment_b5',
 'Accusé de réception — votre dossier',
 'Accusé de réception B5 — sujet',
 'Notification au déclarant confirmant la réception officielle du dossier',
 'TEXT', 'NOTIFICATIONS'),
('notif_content_acknowledgment_b5',
 'L''ASCE-LC accuse réception de votre dossier et vous informera des suites dans les meilleurs délais.',
 'Accusé de réception B5 — contenu',
 'Notification au déclarant confirmant la réception officielle du dossier',
 'TEXT', 'NOTIFICATIONS'),

('notif_subject_complement_request',
 'Information complémentaire requise — votre dossier',
 'Demande de complément — sujet',
 'Notification au déclarant lorsqu''un complément d''information est demandé',
 'TEXT', 'NOTIFICATIONS'),
('notif_content_complement_request',
 'L''ASCE-LC a besoin d''informations supplémentaires. Motif : {motif}',
 'Demande de complément — contenu',
 'Notification au déclarant lorsqu''un complément d''information est demandé. Utilisez {motif} pour insérer le motif saisi par l''agent.',
 'TEXT', 'NOTIFICATIONS'),

('notif_subject_investigation_assignment',
 'Vous avez été affecté(e) à l''investigation — {numero}',
 'Affectation investigation — sujet',
 'Notification à l''agent affecté à une investigation. Utilisez {numero} pour insérer le numéro du dossier.',
 'TEXT', 'NOTIFICATIONS'),
('notif_content_investigation_assignment',
 'Rôle : {role} · Dossier : {objet}',
 'Affectation investigation — contenu',
 'Notification à l''agent affecté à une investigation. Utilisez {role} pour le rôle attribué et {objet} pour l''objet du dossier.',
 'TEXT', 'NOTIFICATIONS'),

('notif_subject_deadline_ar',
 'ALERTE : Délai dépassé — {numero}',
 'Délai AR dépassé — sujet',
 'Alerte automatique quand le délai légal d''accusé de réception (7 jours) est dépassé. Utilisez {numero} pour insérer le numéro du dossier.',
 'TEXT', 'NOTIFICATIONS'),
('notif_content_deadline_ar',
 'Le délai légal de 7 jours pour l''envoi de l''accusé de réception B5 est dépassé pour le dossier {numero}. Action requise immédiatement.',
 'Délai AR dépassé — contenu',
 'Alerte automatique quand le délai légal d''accusé de réception (7 jours) est dépassé. Utilisez {numero} pour insérer le numéro du dossier.',
 'TEXT', 'NOTIFICATIONS'),

('notif_subject_deadline_complement',
 'ALERTE : Complément non reçu — {numero}',
 'Délai complément dépassé — sujet',
 'Alerte automatique quand le délai de réception d''un complément d''information (14 jours) est dépassé. Utilisez {numero} pour insérer le numéro du dossier.',
 'TEXT', 'NOTIFICATIONS'),
('notif_content_deadline_complement',
 'Le délai de 14 jours pour recevoir le complément d''information est dépassé pour le dossier {numero}.',
 'Délai complément dépassé — contenu',
 'Alerte automatique quand le délai de réception d''un complément d''information (14 jours) est dépassé. Utilisez {numero} pour insérer le numéro du dossier.',
 'TEXT', 'NOTIFICATIONS'),

('notif_subject_deadline_investigation',
 'ALERTE : Investigation dépassée — {numero}',
 'Délai investigation dépassé — sujet',
 'Alerte automatique quand le délai réglementaire d''investigation (90 jours) est dépassé. Utilisez {numero} pour insérer le numéro du dossier.',
 'TEXT', 'NOTIFICATIONS'),
('notif_content_deadline_investigation',
 'L''investigation du dossier {numero} dépasse le délai réglementaire de 90 jours. Une prolongation doit être validée par le CGEA et le CGE.',
 'Délai investigation dépassé — contenu',
 'Alerte automatique quand le délai réglementaire d''investigation (90 jours) est dépassé. Utilisez {numero} pour insérer le numéro du dossier.',
 'TEXT', 'NOTIFICATIONS')

ON CONFLICT (config_key)
DO NOTHING;
