package gov.bf.ascelc.univers_audits.enums;

public enum NotificationType {
    RECEIPT_B4,
    ACKNOWLEDGMENT_B5,
    COMPLEMENT_REQUEST,
    INADMISSIBILITY_DECISION,
    TRANSFER_DECISION,
    FINAL_DECISION,
    DEADLINE_ALERT,
    INTERNAL_ALERT,
    STATUS_UPDATE,
    INVESTIGATION_ALERT,
    INVESTIGATION_ASSIGNMENT
}