spring.datasource.url=jdbc:postgresql://postgres:5432/bd_univers_audit
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/asce-lc
keycloak.admin.server-url=http://keycloak:8080
spring.data.redis.host=redis
spring.data.redis.port=6379
storage.upload-dir=/app/uploads
app.api-base-url=https://api.asce-lc.bf
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
spring.jpa.show-sql=false
logging.level.root=WARN
logging.level.gov.bf.ascelc=INFO
logging.level.org.springframework.security=WARN
logging.level.org.springframework.mail=WARN
logging.level.org.hibernate.SQL=WARN
logging.file.name=/app/logs/univers-audits.log
logging.file.max-size=10MB
logging.file.max-history=30