spring.application.name=univers-audits
server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/bd_univers_audit
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/asce-lc


asce.admin.keycloak-sub=${ASCE_ADMIN_SUB:eed35363-ade5-4204-8b37-83fd21947e0b}


spring.mail.host=mailer.gov.bf
spring.mail.port=587
spring.mail.username=denoncer.dsida@asce-lc.bf
spring.mail.password=Asce@2024
spring.mail.properties.mail.smtp.auth=true
spring.mail.from=${spring.mail.username}
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.transport.protocol=smtp


# ?? Africa's Talking SMS ??????????????????????????????????????
africastalking.username=sandbox
africastalking.apiKey=${AT_API_KEY:atsk_8d89c0e4f1a4fc6fd96dc2d004d8e3de69fa70a8e7d6d908e27d03ff1492a71dfa9e12e8

}
africastalking.senderId=ASCELC
africastalking.apiUrl=https://api.sandbox.africastalking.com/version1/messaging
sms.enabled=false

# Prod ? décommente et remplace username par ton vrai compte
# africastalking.username=${AT_USERNAME}
# africastalking.apiUrl=https://api.africastalking.com/version1/messaging

# ?? Async (pour les envois en arrière-plan) ???????????????????
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=5
spring.task.execution.pool.queue-capacity=100

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=Asce2021
spring.data.redis.timeout=2000ms
spring.cache.type=redis
spring.cache.redis.time-to-live=600000


spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true


spring.task.scheduling.pool.size=5


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html


management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always


storage.upload-dir=C:/asce-lc/uploads
storage.max-file-size=26214400
storage.signed-url-expiry=15


logging.level.root=INFO
logging.level.gov.bf.ascelc=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%thread]){magenta} %clr(%logger{36}){cyan} - %msg%n


logging.file.name=C:/asce-lc/logs/univers-audits.log
logging.file.max-size=10MB
logging.file.max-history=30


# ?? Keycloak Admin Client ?????????????????????????????????????
keycloak.admin.server-url=http://localhost:8080
keycloak.admin.realm=asce-lc
keycloak.admin.client-id=asce-lc-backend
keycloak.admin.client-secret=${KEYCLOAK_CLIENT_SECRET:wK2sXd4ovtG3KlYhN8IbkPJfE1nhFfT3}
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG